name: vcore_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com



environment:
  sdk: '>=1.12.0-dev.5.10 <2.0.0'

dependencies:
  vcore:
    path: ../vcore
  analyzer: '>=0.27.1 <0.28.0'
  built_collection: '^1.0.1'
#  built_json: '^0.0.5'
  source_gen: '>=0.4.3 <0.5.0'
  quiver: '>=0.21.0 <0.22.0'

dev_dependencies:
#  built_value: '^0.0.6'
#  built_value_generator: '^0.0.6'
  test: '>=0.12.0 <0.13.0'
