description: "A starting point for Dart libraries or applications."
name: "vcore_generator"
version: "0.0.1"
dependencies: 
  analyzer: ">=0.27.1 <0.28.0"
  built_collection: "^1.0.1"
  built_json_generator: "^0.0.5"
  quiver: ">=0.21.0 <0.22.0"
  source_gen: ">=0.4.3 <0.5.0"
  vcore: 
    path: "../vcore"
dev_dependencies: 
  test: ">=0.12.0 <0.13.0"
environment: 
  sdk: ">=1.12.0-dev.5.10 <2.0.0"
